### ISSUE TITLE
JoinGame broke

### ISSUE THREAD

**Issue by LarvenStein** [LarvenStein/multiplayer-hangman-api#8]
Users are unable to join games via WebSockets. Here is the error from the logs:
```
fail: Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher[8]
      Failed to invoke hub method 'JoinGame'.
      System.InvalidOperationException: Sequence contains no elements
         at System.Linq.ThrowHelper.ThrowNoElementsException()
         at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
         at Dapper.SqlMapper.ThrowZeroRows(Row row) in /_/Dapper/SqlMapper.cs:line 1257
         at Dapper.SqlMapper.QueryRowAsync[T](IDbConnection cnn, Row row, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 503
         at Hangman.Application.Repository.UserRepository.GetGameLeader(String gameCode, CancellationToken cancellationToken) in /src/src/Hangman.Apllication/Repository/UserRepository.cs:line 35
         at Hangman.Application.Services.GameService.JoinGameAsync(Player player, CancellationToken token) in /src/src/Hangman.Apllication/Services/GameService.cs:line 65
         at Hangman.Api.Hubs.GameHub.JoinGame(String roomCode, String nickname, IGameService gameService, IUserService userService) in /src/src/Hangman.Api/Hubs/Roundhub.cs:line 34
         at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.ExecuteMethod(ObjectMethodExecutor methodExecutor, Hub hub, Object[] arguments)
         at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.<Invoke>g__ExecuteInvocation|18_0(DefaultHubDispatcher`1 dispatcher, ObjectMethodExecutor methodExecutor, THub hub, Object[] arguments, AsyncServiceScope scope, IHubActivator`1 hubActivator, HubConnectionContext connection, HubMethodInvocationMessage hubMethodInvocationMessage, Boolean isStreamCall)

```

**Comment by LarvenStein** [comment]
This doesn't seem like a bug with the software, more like a problem with the database, as the word lists endpoint returns an empty array: `[]`.

Maybe a mechanism to check the databases' health would be a good idea.
